### ISSUE TITLE
How to set up a BYE ?

### ISSUE THREAD

**Issue by peterlondon1** [sbachinin/playoffs#4]
If the number of players is NOT a power of 2, e.g. there are 61 players instead of 64, then some players get a BYE (free pass to the second round).

How can this be done? e.g.  I want (in singles) the lower side of a match to show "BYE". I can leave the contestantId empty, but then it just shows as blank.

**Comment by sbachinin** [comment]
You have 2 options:
1) instead of contestantId, provide { title: "BYE" } for a side.
2) provide a contestantId that points to a contestant object where
players[0].title is "BYE"
"some_id_for_bye": {
    "players": [
        {
            "title": "BYE",
        }
    ]
}

You may encounter a problem with text alignment. Possibly "BYE" will appear
at the very left while normal players' names are pushed more to the right
by entryStatus or nationality (if you have these).
Let me know if you will experience such a problem.
It will be easier to solve if you choose the second option.

**Comment by sbachinin** [comment]
No, actually the 1st option is preferable.
In case of alignment problems you can provide an html string for a
side.title and place the "BYE" text where you want. Smth like this:
"sides": [
    {
        "title": `<p style="margin-left: 60px">BYE</p>`
    }
]

**Comment by peterlondon1** [comment]
Thanks @sbachinin . I gave that a try and it seems fine!
